<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>hcl</string>
   </array>
  <key>name</key>
  <string>hclrs</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.hclrs</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(register)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regfile_decl</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\};?)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(wire)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(const)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__4</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#builtin_vars</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#wire_ident</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#regfile_access</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>bool_expr</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#regfile_access</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#wire_ident</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#slice</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(&amp;&amp;|\|\|)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>((==)|(!=)|(&lt;=)|(&gt;=)|&lt;|&gt;)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\bin\b)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>keyword.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#bool_expr__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#bool_expr__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>bool_expr__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\{)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#slice</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#regfile_access</string>
        </dict>
       </array>
    </dict>
    <key>bool_expr__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#bool_expr</string>
        </dict>
       </array>
    </dict>
    <key>builtin_vars</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((reg_[a-zA-Z]+)|(stall_[a-zA-Z])|(bubble_[a-zA-Z])|(valE)|(valM)|(dst_E)|(dst_M)|(\bStat\b)|(mem_[a-zA-Z]+)|(\bpc\b))</string>
          <key>name</key>
          <string>entity.name.function.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>((#.*)|(//.*))</string>
          <key>name</key>
          <string>comment.hclrs</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
       </array>
    </dict>
    <key>const_keyword</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([A-Z_]+)</string>
          <key>name</key>
          <string>constant.numeric.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?=[a-zA-Z]+[a-zA-Z0-9]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#wire_spec</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,|(?=;))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#wire_ident</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#mux</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#regfile_access</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#wire_ident</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#slice</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bool_expr</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.hclrs</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.hclrs</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>mux</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#mux__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>mux__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(1(?!\d))</string>
          <key>name</key>
          <string>constant.numeric.hclrs</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#builtin_vars</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bool_expr</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#mux__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\.)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
       </array>
    </dict>
    <key>mux__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#mux</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#builtin_vars</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#regfile_access</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#wire_ident</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#slice</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#bool_expr</string>
        </dict>
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(0x[0-9a-fA-F]+)</string>
          <key>name</key>
          <string>constant.numeric.hclrs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(0b[01]+)</string>
          <key>name</key>
          <string>constant.numeric.hclrs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b\d+)</string>
          <key>name</key>
          <string>constant.numeric.hclrs</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\+|\*|-|/|(&amp;)|(\|)|(\^)|(!)|(~))</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>regfile_access</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>([a-zA-Z](?=_))</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regfile_access__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>([a-zA-Z][a-zA-Z0-9]*\b)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>variable.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>regfile_access__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(_)</string>
          <key>name</key>
          <string>variable.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>regfile_decl</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-z][A-Z])</string>
          <key>name</key>
          <string>variable.hclrs</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#regfile_decl__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>regfile_decl__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(?=[a-zA-Z]+[a-zA-Z0-9]*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>text.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#wire_spec</string>
            </dict>
           </array>
          <key>end</key>
          <string>(,|(?=;))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>include</key>
          <string>#comment</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(;)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>slice</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(\[)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#slice__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\.)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>slice__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(\.\.)</string>
          <key>name</key>
          <string>punctuation.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>wire_ident</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-zA-Z][a-zA-Z0-9]*\b)</string>
          <key>name</key>
          <string>variable.hclrs</string>
        </dict>
       </array>
    </dict>
    <key>wire_spec</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>([a-zA-Z]+[a-zA-Z0-9]*)</string>
          <key>name</key>
          <string>variable.hclrs</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(:)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#wire_spec__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=[\x{002c}\x{003b}])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>wire_spec__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\=)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#wire_spec__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(?=[\x{002c}\x{003b}])</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.hclrs</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>wire_spec__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#const_keyword</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
